package com.tokamak.mobile.android.tokamakai.ui.components

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.tokamak.mobile.android.tokamakai.model.Tracker
import com.tokamak.mobile.android.tokamakai.model.TrackerData
import com.tokamak.mobile.android.tokamakai.model.TrackerType
import com.tokamak.mobile.android.tokamakai.ui.theme.ReflectTheme
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.time.Duration.Companion.seconds

/*
 * A component for controlling value-type trackers.
 *
 * ValueControl is responsible for providing interaction and state management to the stateless
 * composable [Value] generated by Relay. [onLongClick] provides a way for callers to supplement
 * the control's intrinsic interactions with, for example, a context menu.
 */
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun ValueControl(
    trackerData: TrackerData,
    modifier: Modifier = Modifier,
    onLongClick: (() -> Unit)? = null,
) {
    val editDelaySeconds = 3

    val scope = rememberCoroutineScope()
    var countdown by remember { mutableStateOf<Job?>(null) }
    val isEditing = countdown != null
    val endEditing: suspend CoroutineScope.() -> Unit = {
        delay(editDelaySeconds.seconds)
        countdown = null
    }
}

@Preview
@Composable
fun ValueControllerPreview() {
    val data = TrackerData(
        Tracker(
            emoji = "🍕",
            name = "Value",
            type = TrackerType.COUNT
        )
    )
    ReflectTheme {
        Box(
            modifier = Modifier.width(388.dp).height(64.dp)
        ) {
            ValueControl(data)
        }
    }
}